# Generated by Django 5.0.4 on 2024-04-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=350, verbose_name='شماره تلفن')),
            ],
            options={
                'verbose_name': 'مشاوره',
                'verbose_name_plural': 'مشاوره ها',
            },
        ),
    ]
