# Generated by Django 5.0.4 on 2024-04-18 09:26

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_counseling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 18), verbose_name='تاریخ ثبت نام'),
        ),
    ]
