# Generated by Django 5.0.4 on 2024-04-18 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FroumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='عنوان دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی انجمن',
                'verbose_name_plural': 'دسته های انجمن',
            },
        ),
        migrations.CreateModel(
            name='Froum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('froum_name', models.CharField(max_length=350, verbose_name='نام انجمن')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='froum_cat', to='froum.froumcategory', verbose_name='')),
            ],
            options={
                'verbose_name': 'انجمن',
                'verbose_name_plural': 'انجمن ها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.TextField(verbose_name='سوال')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان سوال')),
                ('froum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_froum', to='froum.froum', verbose_name='انجمن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال ها',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='جواب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answer', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_answer', to='froum.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'جواب',
                'verbose_name_plural': 'جواب ها',
            },
        ),
    ]
