# Generated by Django 5.0.4 on 2024-04-20 13:37

import ckeditor_uploader.fields
import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 20), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='سوال'),
        ),
    ]
