# Generated by Django 5.0.4 on 2024-04-20 13:53

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froum', '0002_question_register_date_alter_question_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 20), verbose_name='تاریخ ساخت'),
        ),
    ]
